version: "3.0"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    depends_on: 
      - redis
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - 8091:8081
